### ISSUE TITLE
'exe' mode completes but reports error in the log

### ISSUE THREAD

**Issue by vivek-bala** [radical-experiments/radical.synapse#1]
The 'exe' mode completes (all files are generated, the mdlog file reports successful mdrun), but there is an error reported in the log file:

```
execute: mdrun -nt 1 -o traj.trr -e ener.edr -s topol.tpr -g mdlog.log -cpo state.cpt -c outgro
index mdrun -nt 1 -o traj.trr -e ener.edr -s topol.tpr -g mdlog.log -cpo state.cpt -c outgro ({'step': '10000', 'prob': '1', 'rate': '1'}) to mdrun -nt 1 -o traj.trr -e ener.edr -s topol.tpr -g mdlog.log -cpo state.cpt -c outgro
Traceback (most recent call last):
  File "/home/ubuntu/ves/synapse-exp/bin/radical-synapse-execute", line 16, in <module>
    rsu.store_profile (info, mode='exe')
  File "/home/ubuntu/ves/synapse-exp/local/lib/python2.7/site-packages/radical/synapse/utils/misc.py", line 146, in store_profile
    host = profile['sys'].get ('hostname')
KeyError: 'sys'
```

**Comment by andre-merzky** [comment]
Vivek, is this still an open issue?  Thanks!

**Comment by vivek-bala** [comment]
Yes, I tried it again now. I get the same error. Just to confirm, the 'exe' mode is independent of the other modes right ?
